import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { emissionFactors } from "@/lib/carbonCalculations";

export default function Learn() {
  return (
    <div className="p-6 md:p-8 space-y-8 max-w-4xl mx-auto w-full">
      <div>
        <h1 className="text-3xl font-bold tracking-tight">Education Hub</h1>
        <p className="text-muted-foreground mt-2">Understand the science behind your carbon footprint.</p>
      </div>

      <div className="prose dark:prose-invert max-w-none space-y-8">
        <section>
          <h2>The Global Context</h2>
          <p>
            A carbon footprint is the total amount of greenhouse gases (including carbon dioxide and methane) that are generated by our actions. 
            The global average carbon footprint per person is close to <strong>4 tonnes (4,000 kg) per year</strong>, or about <strong>333 kg per month</strong>.
          </p>
          <p>
            To have the best chance of avoiding a 2℃ rise in global temperatures, the average global carbon footprint per year needs to drop to under 2 tonnes by 2050.
          </p>
        </section>

        <section className="grid grid-cols-1 md:grid-cols-2 gap-6 not-prose">
          <Card>
            <CardHeader>
              <CardTitle>Transport</CardTitle>
              <CardDescription>Major emission factors</CardDescription>
            </CardHeader>
            <CardContent>
              <ul className="space-y-2 text-sm">
                <li className="flex justify-between border-b pb-2"><span>Gasoline Car</span> <span className="font-mono">{emissionFactors.transport.car_gasoline} kg/km</span></li>
                <li className="flex justify-between border-b pb-2"><span>Electric Car</span> <span className="font-mono">{emissionFactors.transport.car_electric} kg/km</span></li>
                <li className="flex justify-between border-b pb-2"><span>Domestic Flight</span> <span className="font-mono">{emissionFactors.transport.flight_domestic} kg/km</span></li>
                <li className="flex justify-between border-b pb-2"><span>Train</span> <span className="font-mono">{emissionFactors.transport.train} kg/km</span></li>
              </ul>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>Food</CardTitle>
              <CardDescription>Impact per kg of food</CardDescription>
            </CardHeader>
            <CardContent>
              <ul className="space-y-2 text-sm">
                <li className="flex justify-between border-b pb-2"><span>Beef</span> <span className="font-mono text-destructive">{emissionFactors.food.beef} kg/kg</span></li>
                <li className="flex justify-between border-b pb-2"><span>Pork</span> <span className="font-mono">{emissionFactors.food.pork} kg/kg</span></li>
                <li className="flex justify-between border-b pb-2"><span>Chicken</span> <span className="font-mono">{emissionFactors.food.chicken} kg/kg</span></li>
                <li className="flex justify-between border-b pb-2"><span>Vegetables</span> <span className="font-mono text-primary">{emissionFactors.food.vegetables} kg/kg</span></li>
              </ul>
            </CardContent>
          </Card>
        </section>

        <section>
          <h2>Common Misconceptions</h2>
          <div className="space-y-4">
            <div className="p-4 border rounded-lg bg-card text-card-foreground not-prose">
              <h4 className="font-bold mb-1">Myth: Eating local is more important than what you eat</h4>
              <p className="text-sm text-muted-foreground">Fact: Transportation accounts for less than 10% of food's greenhouse gas emissions. What you eat (e.g., plant-based vs. beef) matters far more than where it came from.</p>
            </div>
            <div className="p-4 border rounded-lg bg-card text-card-foreground not-prose">
              <h4 className="font-bold mb-1">Myth: Digital usage has no physical footprint</h4>
              <p className="text-sm text-muted-foreground">Fact: Data centers, networks, and device manufacturing consume massive amounts of electricity. The ICT sector accounts for ~3-4% of global emissions.</p>
            </div>
          </div>
        </section>
      </div>
    </div>
  );
}
